;;; site-gentoo.el --- site initialisation for Gentoo-installed packages

;;; Commentary:
;; Automatically generated by elisp-common.eclass
;; DO NOT EDIT THIS FILE

;;; Code:

;;; emacs-24 site-lisp configuration

(when (string-match "\\`24\\.5\\>" emacs-version)
  (let ((path (getenv "INFOPATH"))
	(dir "/usr/share/info/emacs-24")
	(re "\\`/usr/share/info\\>"))
    (and path
	 ;; move Emacs Info dir before anything else in /usr/share/info
	 (let* ((p (cons nil (split-string path ":" t))) (q p))
	   (while (and (cdr q) (not (string-match re (cadr q))))
	     (setq q (cdr q)))
	   (setcdr q (cons dir (delete dir (cdr q))))
	   (setq Info-directory-list (prune-directory-list (cdr p)))))))

;;; emacs-25 site-lisp configuration

(when (string-match "\\`25\\.1\\>" emacs-version)
  (let ((path (getenv "INFOPATH"))
	(dir "/usr/share/info/emacs-25")
	(re "\\`/usr/share/info\\>"))
    (and path
	 ;; move Emacs Info dir before anything else in /usr/share/info
	 (let* ((p (cons nil (split-string path ":" t))) (q p))
	   (while (and (cdr q) (not (string-match re (cadr q))))
	     (setq q (cdr q)))
	   (setcdr q (cons dir (delete dir (cdr q))))
	   (setq Info-directory-list (prune-directory-list (cdr p)))))))
;; 实现自动换行
(add-hook 'org-mode-hook (lambda () (setq truncate-lines nil)))

(require 'electric)
(electric-indent-mode t)
(electric-pair-mode t)
;; ȡ???����???
(setq inhibit-startup-message t)
;; ?????кţ??????к?ռ4λ
(global-linum-mode 1)
(setq linum-format "%4d")

;; ?? dired ???Եݹ??Ŀ?????ɾ??Ŀ¼
(setq dired-recursive-copies 'top)
(setq dired-recursive-deletes 'top)

;; ?????Ự,?´δ???ʱ?ָ?
(desktop-save-mode 1)

;; ʹ??ido??ΪĬ?ϲ??ҹ???
; for Gentoo instaled package.
(ido-mode 1)
(setq ido-enable-flex-matching t)
(setq ido-everywhere t)
(setq ido-use-filename-at-point 'guess)

;; ????ȫ?ֵ?flycheck
(add-hook 'after-init-hook #'global-flycheck-mode)

;; ?? php-mode ?? html-mode ???л?
(defun toggle-php-web-mode ()
  (interactive)
  "Toggle mode between PHP & HTML Helper modes"
  (cond ((string= mode-name "php")
	 (php-mode))
	((string= mode-name "web")
	 (web-mode))))
(global-set-key [f5] 'toggle-php-web-mode)

;; tab ????4?ո?
(setq-default indent-tabs-mode nil)
(setq-default c-basic-offset 4)
(setq-default tab-width 4)

;; ?????۵? ʹ??hook??��????
(add-hook 'c-mode-hook 'hs-minor-mode)
(add-hook 'c++-mode-hook 'hs-minor-mode)  
(add-hook 'python-mode-hook 'hs-minor-mode)  
(add-hook 'web-mode-hook 'hs-minor-mode)  
(add-hook 'php-mode-hook 'hs-minor-mode)  
;--------- about tools moddles ------
(show-paren-mode)
(tool-bar-mode 0)
(menu-bar-mode 0)
(scroll-bar-mode 0)
;-----------------------------------


;--------------- about display -------------
;; ???꿿??????ָ??ʱ????????ָ???Զ?????
;; (mouse-avoidance-mode 'animate)
;; ?ڱ???��??ʾbuffer??????
(setq frame-title-format "emacs@%b")
;; ֱ?Ӵ򿪺???ʾͼƬ
(auto-image-file-mode)
;; ȥ??????С??ͷ
(global-visual-line-mode 1)
;; ??ǰ????ɫ
(require 'hl-line)
(global-hl-line-mode 1)
(set-face-background 'hl-line "#272727")
;-------------------------------------------


;---------------- about Color Themes ---------------------
;; self color theme setting for Gentoo installed package.
(require 'color-theme)
(color-theme-initialize)
;------------------------------------
;; take one choice for color theme: |
;------------------------------------
;(color-theme-blue-mood)       ;
;(color-theme-subtle-hacker)   ;
;(color-theme-shaman)          ;
;(color-theme-resolve)         ;
;(color-theme-marine)          ;
;(color-theme-dark-blue2)      ;
;(color-theme-gnome)           ;
(color-theme-comidia)
;(color-theme-snowish)
;(color-theme-deep-blue)        ;
;                              ;
;-------------------------------
;---------------------------------------------------------
;; set TAB width for c-style 
(setq tab-width 4)
(setq default-tab-width 4)
(setq indent-tabs-mode t)
(setq c-basic-offset 4)

;; C language setting
(add-hook 'c-mode-hook
          '(lambda ()
             (c-set-style "ANSI")
             (setq tab-width 4)
             (setq indent-tabs-mode t)
             (setq c-basic-offset 4)))

;; C++ language setting
(add-hook 'c++-mode-hook
          '(lambda ()
             (c-set-style "ANSI")
             ;;(c-toggle-auto-state)
             (setq tab-width 4)
             (setq indent-tabs-mode t)
             (setq c-basic-offset 4)))
(require 'compile)
(add-hook 'c-mode-hook
					(lambda ()
						(unless (file-exists-p "Makefile")
							(set (make-local-variable 'compile-command)
										 (let ((file (file-name-nondirectory buffer-file-name)))
										 (format "%s -c -o %s.o %s %s %s"
														 (or (getenv "CC") "gcc")
														 (file-name-sans-extension file)
														 (or (getenv "CPPFLAGS") "-DDEBUG=9")
														 (or (getenv "CFLAGS") "-ansi -pedantic -std=c11 -Wall -g")
															 file))))))
	
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))

(setq web-mode-engines-alist
			'(("php"    . "\\.phtml\\'")
				("blade"  . "\\.blade\\."))
			)

(add-to-list 'auto-mode-alist '("\\.api\\'" . web-mode))
(setq web-mode-content-types-alist
			'(("json" . "/some/path/.*\\.api\\'")
				("xml"  . "/other/path/.*\\.api\\'")
				("jsx"  . "/some/react/path/.*\\.js[x]?\\'")))


;;; dev-perl/Perl-Critic site-lisp configuration
(add-to-list 'load-path "/usr/share/emacs/site-lisp/Perl-Critic")

(autoload 'perlcritic "perlcritic" "" t)
(autoload 'perlcritic-region "perlcritic" "" t)
(autoload 'perlcritic-mode "perlcritic" "" t)

;;; auto-run for cperl-mode and perl-mode
;;
;; (eval-after-load "cperl-mode"
;;  '(add-hook 'cperl-mode-hook 'perlcritic-mode))
;; (eval-after-load "perl-mode"
;;  '(add-hook 'perl-mode-hook 'perlcritic-mode))

;;; async site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/async")
(load "async-autoloads" nil t)

;;; auto-complete site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/auto-complete")
;;(load "auto-complete-autoloads" nil t)
(load "auto-complete-autoloads" 1 t)
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "/usr/share/emacs/site-lisp/auto-complete/dict")
(ac-config-default)

;;; autoconf-mode site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/autoconf-mode")
(autoload 'autoconf-mode "autoconf-mode"
  "Major mode for editing autoconf files." t)
(autoload 'autotest-mode "autotest-mode"
  "Major mode for editing autotest files." t)
(add-to-list 'auto-mode-alist
	     '("\\.ac\\'\\|configure\\.in\\'" . autoconf-mode))
(add-to-list 'auto-mode-alist
	     '("\\.at\\'" . autotest-mode))

;;; cmake site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/cmake")
(autoload 'cmake-mode "cmake-mode" "Major mode for editing CMake files." t)
(add-to-list 'auto-mode-alist '("CMakeLists\\.txt\\'" . cmake-mode))
(add-to-list 'auto-mode-alist '("\\.cmake\\'" . cmake-mode))

;;; color-theme site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/color-theme")

(autoload (quote color-theme-select) "color-theme" "\
Displays a special buffer for selecting and installing a color theme.
With optional prefix ARG, this buffer will include color theme libraries
as well.  A color theme library is in itself not complete, it must be
used as part of another color theme to be useful.  Thus, color theme
libraries are mainly useful for color theme authors." t nil)

(autoload (quote color-theme-describe) "color-theme" "\
Describe color theme listed at point.
This shows the documentation of the value of text-property color-theme
at point.  The text-property color-theme should be a color theme
function.  See `color-themes'." t nil)

(autoload (quote color-theme-install-at-mouse) "color-theme" "\
Install color theme clicked upon using the mouse.
First argument EVENT is used to set point.  Then
`color-theme-install-at-point' is called." t nil)

(autoload (quote color-theme-install-at-point-for-current-frame) "color-theme" "\
Install color theme at point for current frame only.
Binds `color-theme-is-global' to nil and calls
`color-theme-install-at-point'." t nil)

(autoload (quote color-theme-print) "color-theme" "\
Print the current color theme function.

You can contribute this function to <URL:news:gnu.emacs.sources> or
paste it into your .emacs file and call it.  That should recreate all
the settings necessary for your color theme.

Example:

    (require 'color-theme)
    (defun my-color-theme ()
      \"Color theme by Alex Schroeder, created 2000-05-17.\"
      (interactive)
      (color-theme-install
       '(...
	 ...
	 ...)))
    (my-color-theme)

If you want to use a specific color theme function, you can call the
color theme function in your .emacs directly.

Example:

    (require 'color-theme)
    (color-theme-gnome2)" t nil)

(autoload (quote color-theme-analyze-defun) "color-theme" "\
Once you have a color-theme printed, check for missing faces.
This is used by maintainers who receive a color-theme submission
and want to make sure it follows the guidelines by the color-theme
author." t nil)

(autoload (quote color-theme-make-snapshot) "color-theme" "\
Return the definition of the current color-theme.
The function returned will recreate the color-theme in use at the moment." nil nil)

(autoload (quote color-theme-compare) "color-theme" "\
Compare two color themes.
This will print the differences between installing THEME-A and
installing THEME-B.  Note that the order is important: If a face is
defined in THEME-A and not in THEME-B, then this will not show up as a
difference, because there is no reset before installing THEME-B.  If a
face is defined in THEME-B and not in THEME-A, then this will show up as
a difference." t nil)

(autoload (quote color-theme-install) "color-theme" "\
Install a color theme defined by frame parameters, variables and faces.

The theme is installed for all present and future frames; any missing
faces are created.  See `color-theme-install-faces'.

THEME is a color theme definition.  See below for more information.

If you want to install a color theme from your .emacs, use the output
generated by `color-theme-print'.  This produces color theme function
which you can copy to your .emacs.

A color theme definition is a list:
\([FUNCTION] FRAME-PARAMETERS VARIABLE-SETTINGS FACE-DEFINITIONS)

FUNCTION is the color theme function which called `color-theme-install'.
This is no longer used.  There was a time when this package supported
automatic factoring of color themes.  This has been abandoned.

FRAME-PARAMETERS is an alist of frame parameters.  These are installed
with `color-theme-install-frame-params'.  These are installed last such
that any changes to the default face can be changed by the frame
parameters.

VARIABLE-DEFINITIONS is an alist of variable settings.  These are
installed with `color-theme-install-variables'.

FACE-DEFINITIONS is an alist of face definitions.  These are installed
with `color-theme-install-faces'.

If `color-theme-is-cumulative' is nil, a color theme will undo face and
frame-parameter settings of previous color themes." nil nil)

(autoload (quote color-theme-submit) "color-theme" "\
Submit your color-theme to the maintainer." t nil)

(autoload (quote color-theme-initialize) "color-theme" "\
Initialize the color theme package by loading color-theme-libraries." t nil)

;;; company site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/company")
(load "company-autoloads" nil t)

;;; cscope site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/cscope")

(autoload 'cscope-minor-mode "xcscope")
(autoload 'cscope-display-buffer "xcscope"
  "Display the *cscope* buffer." t)
(autoload 'cscope-display-buffer-toggle "xcscope"
  "Toggle cscope-display-cscope-buffer, which corresponds to
\"Auto display *cscope* buffer\"." t)
(autoload 'cscope-next-symbol "xcscope"
  "Move to the next symbol in the *cscope* buffer." t)
(autoload 'cscope-next-file "xcscope"
  "Move to the next file in the *cscope* buffer." t)
(autoload 'cscope-prev-symbol "xcscope"
  "Move to the previous symbol in the *cscope* buffer." t)
(autoload 'cscope-prev-file "xcscope"
  "Move to the previous file in the *cscope* buffer." t)
(autoload 'cscope-pop-mark "xcscope"
  "Pop back to where cscope was last invoked." t)
(autoload 'cscope-set-initial-directory "xcscope"
  "Set the cscope-initial-directory variable." t)
(autoload 'cscope-unset-initial-directory "xcscope"
  "Unset the cscope-initial-directory variable." t)
(autoload 'cscope-find-this-symbol "xcscope"
  "Locate a symbol in source code." t)
(autoload 'cscope-find-global-definition "xcscope"
  "Find a symbol's global definition." t)
(autoload 'cscope-find-global-definition-no-prompting "xcscope"
  "Find a symbol's global definition without prompting." t)

(defun cscope:hook ()
  (cscope-minor-mode))
(add-hook 'c-mode-hook 'cscope:hook)
(add-hook 'c++-mode-hook 'cscope:hook)
(add-hook 'dired-mode-hook 'cscope:hook)

;;; site-lisp configuration for cython-mode

(add-to-list 'load-path "/usr/share/emacs/site-lisp/cython")

(autoload  'cython-mode "cython-mode" "Major mode for editing Cython files" t)
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.pyx\\'" . cython-mode))
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.pxd\\'" . cython-mode))
;;;###autoload
(add-to-list 'auto-mode-alist '("\\.pxi\\'" . cython-mode))

;;; dash site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/dash")

;;; desktop-file-utils site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/desktop-file-utils")
(autoload 'desktop-entry-mode "desktop-entry-mode" "Desktop Entry mode" t)
(add-to-list 'auto-mode-alist
 '("\\.desktop\\(\\.in\\)?$" . desktop-entry-mode))
(add-hook 'desktop-entry-mode-hook 'turn-on-font-lock)

;;; dropdown-list site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/dropdown-list")
(autoload 'dropdown-list "dropdown-list")

;;; elpy site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/elpy")
(load "elpy-autoloads" nil t)

;;; epl site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/epl")
(load "epl-autoloads" nil t)

;;; eselect-mode site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/eselect-mode")
(autoload 'eselect-mode "eselect-mode" "Major mode for .eselect files." t)
(add-to-list 'auto-mode-alist '("\\.eselect\\'" . eselect-mode))

;;; find-file-in-project site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/find-file-in-project")
(load "find-file-in-project-autoloads" nil t)

;;; flx site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/flx")
(load "flx-autoloads" nil t)

;;; flx-ido site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/flx-ido")
(load "flx-ido-autoloads" nil t)

;;; flycheck site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/flycheck")
(load "flycheck-autoloads" nil t)

;;; dev-vcs/git site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/git")
(autoload 'git-status "git" "Entry point into git-status mode." t)
;;(autoload 'git-blame-mode "git-blame"
;;  "Minor mode for incremental blame for Git." t)

;; GNU Emacs >=22.2 already includes vc-git.el.
;; Enable the following only if Emacs has no GIT support.
(unless (fboundp 'vc-git-registered)
  (add-to-list 'load-path "/usr/share/emacs/site-lisp/git/compat")
  (add-to-list 'vc-handled-backends 'GIT))
(add-to-list 'load-path "/usr/share/emacs/plugins/async")
(add-to-list 'load-path "/usr/share/emacs/plugins/helm")
(require 'helm-config)
;(require 'helm)
;(helm-mode 1)

;;; highlight-indentation site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/highlight-indentation")
(load "highlight-indentation-autoloads" nil t)

;;; ido-at-point site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/ido-at-point")
(load "ido-at-point-autoloads" nil t)

;;; ido-completing-read+ site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/ido-completing-read+")
(load "ido-completing-read+-autoloads" nil t)

;;; ido-ubiquitous site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/ido-ubiquitous")
(load "ido-ubiquitous-autoloads" nil t)

;;; idomenu site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/idomenu")
(load "idomenu-autoloads" nil t)

;;; ivy site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/ivy")
(load "ivy-autoloads" nil t)
(global-set-key (kbd "C-SPC") 'nil)
;; kill buf and window
(global-set-key (kbd "s-0") 'kill-buffer-and-window)
;; skip to other window, and mask default key-group
(global-set-key (kbd "C-x o") 'nil)
(global-set-key (kbd "s-o") 'other-window)
;; set start neotree mode with <f8>
(global-set-key [f8] 'neotree-toggle)

;; compile c command file with gcc
(global-set-key (kbd "s-c s-c") 'compile)
;; open a shell with new windows
(global-set-key (kbd "s-e") 'eshell)
;; php ?? html ģʽ?л?,ʵ?ִ???λ??50phpmode-gentoo.el ??50mmm-mode-gentoo.el??һ????
(global-set-key [f5] 'toggle-php-html-mode)
;; ?????۵????ݼ?
(global-set-key (kbd "s-- s--") 'hs-hide-all)
(global-set-key (kbd "s-- -") 'hs-hide-block)
(global-set-key (kbd "s-- 0") 'hs-hide-level)
(global-set-key (kbd "s-= s-=") 'hs-show-all)
(global-set-key (kbd "s-= =") 'hs-show-block)

;;; let-alist site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/let-alist")
(load "let-alist-autoloads" nil t)

;;; libidn site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/libidn")
(autoload 'idna-to-ascii "idna"
  "Returns an ASCII Compatible Encoding (ACE) of STR.")
(autoload 'idna-to-unicode "idna"
  "Returns a possibly multibyte string after decoding STR.")
(autoload 'punycode-encode "punycode"
  "Returns a Punycode encoding of STR.")
(autoload 'punycode-decode "punycode"
  "Returns a possibly multibyte string which is the punycode decoding of STR.")
;; Load site initialisation for personal linum mode.
(add-to-list 'load-path "/usr/share/emacs/plugins/linum")
(set-language-environment 'UTF-8)
(set-locale-environment "UTF-8")

;; Setting English Font
(set-face-attribute
  'default nil :font "Liberation Mono 10")


;; Chinese Font
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font (frame-parameter nil 'font)
					charset
					(font-spec :family "Microsoft Yahei" :size 12)))

;;; lua-mode site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/lua-mode")
(autoload 'lua-mode "lua-mode" "Mode for editing Lua scripts" t)
(add-to-list 'auto-mode-alist '("\\.lua\\'" . lua-mode))
(setq lua-default-application "/usr/bin/lua")

;;; mmm-mode site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/mmm-mode")
(require 'mmm-auto)
(setq mmm-global-mode 'maybe)
;; with php-mode
(mmm-add-mode-ext-class nil "\\.php3?\\'" 'html-php)
(mmm-add-classes
  '((html-php
      :submode php-mode
      :front "<\\?\\(php\\)?"
      :back "\\?>")))
(autoload 'php-mode "php-mode" "PHP editing mode" t)
(add-to-list 'auto-mode-alist '("\\.php3?\\'" . sgml-html-mode))


;;; monokai-theme site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/monokai-theme")
(load "monokai-theme-autoloads" nil t)

;;; neotree site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/neotree")
(load "neotree-autoloads" nil t)

;;; org-mode site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/org-mode")
(add-to-list 'auto-mode-alist '("\\.org\\'" . org-mode))

;;; php-mode site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/php-mode")
(autoload 'php-mode "php-mode" "Major mode for editing PHP code." t)
(add-to-list 'auto-mode-alist '("\\.php[s34]?\\'" . php-mode))
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . php-mode))
(add-to-list 'auto-mode-alist '("\\.inc\\'" . php-mode))
(setq php-manual-path "/usr/share/emacs/doc/php-ch/")

;;; pkg-info site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/pkg-info")
(load "pkg-info-autoloads" nil t)

;;; po-mode site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/po-mode")
(autoload 'po-mode "po-mode" "Major mode for translators to edit PO files" t)
(or (fboundp 'po-find-file-coding-system)
    (autoload 'po-find-file-coding-system "po-compat"))

(add-to-list 'auto-mode-alist '("\\.po\\'\\|\\.po\\." . po-mode))
(modify-coding-system-alist 'file "\\.po\\'\\|\\.po\\."
			    'po-find-file-coding-system)

;;; popup site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/popup")
(load "popup-autoloads" nil t)

;;; pyvenv site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/pyvenv")
(load "pyvenv-autoloads" nil t)

;;; ruby-mode site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/ruby-mode")

(autoload 'ruby-mode "ruby-mode" "Major mode to edit ruby files." t)

(add-to-list 'auto-mode-alist '("Rakefile\\'" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.\\(rake\\|rb\\)\\'" . ruby-mode))
(add-to-list 'interpreter-mode-alist  '("ruby" . ruby-mode))

(autoload 'run-ruby "inf-ruby" "Run an inferior Ruby process" t)
(autoload 'inf-ruby-keys "inf-ruby" "Set local key defs for inf-ruby in ruby-mode")

(add-hook 'ruby-mode-hook 'inf-ruby-keys)
;(add-hook 'ruby-mode-hook 'robe-mode)
;(add-hook 'ruby-mode-hook 'yard-mode)
;(add-hook 'enh-ruby-mode-hook 'robe-mode)
;(add-hook 'enh-ruby-mode-hook 'yard-mode)

(add-to-list 'auto-mode-alist '("\\.rb$" . ruby-mode))
(add-to-list 'auto-mode-alist
	     '("\\(?:\\.rb\\|ru\\|rake\\|thor\\|jbuilder\\|gemspec\\|podspec\\|/\\(?:Gem\\|Rake\\|Cap\\|Thor\\|Vagrant\\|Guard\\|Pod\\)file\\)\\'" . ruby-mode))

;;; seq site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/seq")
(load "seq-autoloads" nil t)
(add-to-list 'load-path "~/.emacs.d/plugins/tabbar/")
(require 'tabbar)
(tabbar-mode 1)

;; style set:
; ????Ĭ??????: ????, ??????ǰ????ɫ????С
(set-face-attribute 'tabbar-default nil
					:family "DejaVu Sans Mono"
					:background "gray80"
					:foreground "gray30"
					:height 1.0
					)
; ???????߰?ť???ۣ????????ߴ?С????ɫ
(set-face-attribute 'tabbar-button nil
					:inherit 'tabbar-default
					:background "gray80"
					:box '(:color "gray80")
					)
; ???õ?ǰtab???ۣ???ɫ?????壬??????С????ɫ
(set-face-attribute 'tabbar-selected nil
					:inherit 'tabbar-default
					:foreground "#104E8B"
					:background "#98FB98"
					:box '(:line-width 1 :color "#98FB98")
					:overline "gray80"
					)
; ???÷ǵ?ǰtab???ۣ???????С????ɫ
(set-face-attribute 'tabbar-unselected nil
					:inherit 'tabbar-default
					:foreground "#104E8B"
					:box '(:line-width 3 :color "#DBDBDB")
					)
(custom-set-variables '(tabbar-separator (quote (0.5))))

(global-set-key [(meta i)] 'tabbar-backward)
(global-set-key [(meta o)] 'tabbar-forward)

;;; web-mode site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/web-mode")
(load "web-mode-autoloads" nil t)

;;; wgrep site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/wgrep")
(require 'wgrep)

;;; window-numbering site-lisp configuration

(add-to-list 'load-path "/usr/share/emacs/site-lisp/window-numbering")
(load "window-numbering-autoloads" nil t)
;(add-to-list 'load-path "/usr/share/emacs/plugins/yasnippet")
;(require 'yasnippet)
;(yas/global-mode 1)


(provide 'site-gentoo)

;; Local Variables:
;; no-byte-compile: t
;; buffer-read-only: t
;; End:

;;; site-gentoo.el ends here
